SECRETS:
  # SSID: <network ssid>
  # MQTT_SERVER: <ip address of mqtt server>
  # CLIENT_NAME: <mqtt client name (can be anything)>
  # MQTT_PORT: <mqtt port (default is 1883)>
  # T1: <mqtt topic 1>
  # T2: <mqtt topic 2>
  # INTERFACE: <wireless/wired name (use ifconfig to find interface names)>
  SSID: NETGEAR15
  MQTT_SERVER: 192.168.0.55
  CLIENT_NAME: thePi
  MQTT_PORT: 1883
  T1: apt
  T2: livingroom
  INTERFACE: wlan0